Repository Drande/Ghost-Whisperer-Anne-s-Diary, pull requests merged in 2024-07, with the labels that each got.

#5 Add skip and pause button for dialogs
  Assets/Prefabs/UI/Game Interface.prefab
  Assets/Scenes/Main Menu.unity
  Assets/Scenes/Minigames/Puzzle Assembly.unity
  Assets/Scripts/Managers/GameManager.cs
  Assets/Scripts/Managers/UIManager.cs
  Assets/Scripts/Utilities/MessageInScreen.cs
  Assets/Scripts/Utilities/PauseToggler.cs
  Assets/Scripts/Utilities/PauseToggler.cs.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: enhancement

#7 Update writetext coroutine to be framerate independent
  Assets/Scripts/Dialogs/ChapterTwoDialogsInGame.cs
  Assets/Scripts/Utilities/Coroutines.cs
  Assets/Scripts/Utilities/MessageInScreen.cs
Labels: bug

#8 Remove unicode characters from chapter dialogs
  Assets/Scripts/Dialogs/AfterChapterOneDialogs.cs
  Assets/Scripts/Dialogs/AfterChapterThreeDialogs.cs
  Assets/Scripts/Dialogs/AfterChapterTwoDialogs.cs
  Assets/Scripts/Dialogs/AfterFailChapterThreeDialog.cs
  Assets/Scripts/Dialogs/AfterFailChapterTwoDialogs.cs
  Assets/Scripts/Dialogs/ChapterOneDialogs.cs
  Assets/Scripts/Dialogs/ChapterThreeDialogs.cs
  Assets/Scripts/Dialogs/ChapterTwoDialogs.cs
  Assets/Scripts/Dialogs/ChapterTwoDialogsInGame.cs
Labels: bug

#12 Fix load current chapter configuration on main menu
  Assets/Scripts/Managers/GameManager.cs
  Assets/Scripts/Managers/UIManager.cs
Labels: bug

#18 Character Controller added
  Assets/Characters/Anne's Texture/Anne 1.prefab
  Assets/Scenes/CharacterControllerScene.unity
  Assets/Scenes/CharacterControllerScene.unity.meta
  Assets/Scripts/Camera.meta
  Assets/Scripts/Camera/CameraController.cs
  Assets/Scripts/Camera/CameraController.cs.meta
  Assets/Scripts/Character.meta
  Assets/Scripts/Character/CharacterMovement.cs
  Assets/Scripts/Character/CharacterMovement.cs.meta
Labels: Develop
